### ISSUE TITLE
identifier as only one property

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#1]
One specific point needs attention from the Geonovum side.

About the [Identifier](https://geonovum.github.io/uml2json/document.html#toc37)

It is stated now that a feature type can have only one property with the IsID = true tag and that it needs to be a simple type.

In NEN 3610 (Dutch base standard for geo-information) we have two properties that contain the id information. One named, identification and one named domain. This is a flattened version of the former NEN3610id complex data type. It is a conceptual id. Each technical implementation can define its own mapping to an operational id. However in the data transfer both the conceptual as well as the operational id are exchanged.

Question is if this works with this requirement class?

**Comment by PalmJanssen** [comment]
For discussion:
This would imply that NEN 3610 expects a kind of jsonID (like the GMLid). An id that acts as the JSON implementation of a conceptual id and works as an operational link/pointer mechanism within the JSON context.

Depending on the construct of the conceptual id. The JSONid is a copy or a mapping from the conceptual id.

**Comment by PalmJanssen** [comment]
A good start.
This works if you stay within the JSON context. However if JSON is used only to convey the data, a receiver of the data receives the JSON implementation of the identfier and does not know how to map it to its original id. For this reason the conceptual id is also included.

@ linda, @wilkoquak . What's your opinion?

**Comment by jechterhoff** [comment]
The "community specific conversion mechanism" would also have to include a reversal of the identifier string to the conceptual id values. If that is considered to be too complex, a different approach could be to either a) not omit the isId=true properties at all in the JSON encoding, or b) to omit them only if there is a single such property, whose value type maps to a JSON string or number.

**Comment by PalmJanssen** [comment]
discussion closed for now.
