### ISSUE TITLE
7.2 - pja - TV's for association role

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#10]
In table 2 the association role (or association) is not mentioned as a model element to be extended. Is that correct? Is InlineOrByReference not a metaproperty or TV?

**Comment by jechterhoff** [comment]
The association role is covered by stereotype `<<property>>` (or whatever alternative name we can come up with for that stereotype - see #13) - see last row, second column in table 2. The stereotype is applicable to both UML attributes and association roles, and the inlineOrByReference tag is owned by that stereotype.
