### ISSUE TITLE
7.3.1 - pja - req 1 Single or multiple definition schema

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#14]
Not sure if I understand this well. Is meant that a UML apllication schema will always lead to one JSON schema and not to several? Is that workable for large application schema including well defined sections (packages).

**Comment by jechterhoff** [comment]
The answer is yes. We have made the decision to generate a single JSON Schema file per application schema. See NOTE 2 for a good reason for doing so. Overall, that reduces the schema complexity (where cross-references between packages, when encoded in separate JSON Schema files, could easily lead to the whole lot of files to being loaded by applications anyway).

That being said, we do not have any practical experience yet with use cases where a large JSON Schema would actually break the validation process. That also depends on the validator implementation. If, in the future, such cases occur, one could extend the approach with the option to generate multiple schema files (as described in the UGAS 2020 ER). But then the complexity increases in referencing the right schema file for a given JSON dataset.

**Comment by jechterhoff** [comment]
That would still be possible. Cross-references between schemas - encoded in separate JSON files - are expected. It is just that we do not want to distribute the contents of a single schema across multiple files.

**Comment by PalmJanssen** [comment]
aha, that helps and seems sensible. Verify with @lvdbrink and @wilkoquak

**Comment by lvdbrink** [comment]
sounds good to me
