### ISSUE TITLE
7.3.2 Documentation

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/uml2json#17]
7.3.2 leaves it open whether documentation is or is not included when present in the UML file and describes that in some cases it's better to leave documentation out.  

Shouldn't we then say that it is _recommended_ to leave documentation out of the JSON Schema? 

And/or have a TV to control whether to include or exclude it from the JSON Schema.

**Comment by cportele** [comment]
I would say that the information whether or not to include documentation is not something to encode in the model. It will depend on how the schema is going to be used. One might even want to have both variants. Without documentation for validation (smaller schema documents) and with documentation for other purposes where humans interact with the schema. 

In my view, whether or not to include it is mainly a parameter for the encoding process and it is not something where a recommendation can be made one way or the other.

**Comment by PalmJanssen** [comment]
I would say that no change is needed.

**Comment by lvdbrink** [comment]
> I would say that no change is needed.

I'm fine with that.
