### ISSUE TITLE
7.3.3.9 - pja - jsonFormat. What is the format (or syntax) to express a format in?

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#22]
It's not clear to me in what syntax a format is expressed.  At a first glance also the mentioned doc: https://www.ietf.org/archive/id/draft-bhutton-json-schema-validation-01.txt  is not helpfull

**Comment by jechterhoff** [comment]
Have a look at chapter 7 in the reference, which defines values for the "format" keyword.
