### ISSUE TITLE
7.3.4.2 - pja - figure 13: roleToClass 1

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#23]
For reflection:
Strictly UML speaking the name of an association end reflects the role the feature has towards the source feature in that association. So roleToClass1 must be understood as the role of Class1 as a member in an association with Class3.

A more appropiate name therefore would be roleOfClass1.

Or maybe roleToClass1 must be read as role assigned to class 1 by class 3. In that case the name roleToClass1 comes close.

**Comment by jechterhoff** [comment]
Maybe, to avoid such confusion, we should just rename the association role to "roleX" (and the other association role to "roleY").

**Comment by PalmJanssen** [comment]
Agree.
