### ISSUE TITLE
7.9.3 - pja - Union for property choices not clear

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#27]
The JSON implementation for the union for property choices is not clear to me.
- Does the referencing property exist in instance data? Or is it replaced by one of the properties 'option1' and 'option2'?
- As understood the option1 and option2 properties can also be multiple (n>1). Does that also work?

**Comment by jechterhoff** [comment]
>  Does the referencing property exist in instance data? Or is it replaced by one of the properties 'option1' and 'option2'?

Yes, the property whose type is a union does exist, and contains as value an object (that represents the union "value") with either property option1 or option2.

>  As understood the option1 and option2 properties can also be multiple (n>1). Does that also work?

Yes.
