### ISSUE TITLE
7.11 - pja - encoding of entityType

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#28]
For clarification.

Do I understand correctly that 'entityType' contains the name of the UML Class?

If so, the example below figure 44 can be less abstract like:

{
  “entityType”: “Person”,
  “property”: “dateOfBirth”
}

**Comment by jechterhoff** [comment]
Yes, the `entityType` member is supposed to encode the name of the conceptual type of the JSON object.

Good point regarding the rather abstract example. I've just updated it.
