### ISSUE TITLE
Hosting of JSON Schema file

### ISSUE THREAD

**Issue by jechterhoff** [Geonovum/uml2json#3]
As part of our specification, we decided to create a JSON Schema file with relevant definitions (e.g., for our version of a link object, as well as a measure). In order for that file to be usable by JSON Schema validators, it needs to be published on the web, and served with suitable content type. Can you set up a web server, where the json file is served with mime type `application/schema+json`?

Today, I've successfully tested such a setup with a local Tomcat server. It looks like the Apache HTTP Server can also be configured accordingly (haven't tested this yet).

The location of the published JSON Schema file may change during the OGC process for our document. An according note will be added in the specification. In any case, having a URL that works for the schema would be a good first step, that's why I'm asking. If hosting the file is not possible for you, we might use https://shapechange.net to publish the file instead. However, a URL that belongs to Geonovum would be preferable.

**Comment by lvdbrink** [comment]
A good place for this could be https://register.geostandaarden.nl/, which is a domain owned by Geonovum where we publish all kinds of technical files belonging to standards. We have to figure out what the path should be, happy to get suggestions for this. @PalmJanssen do you agree? 

Also we have to figure out how to set up the mime type correctly and if we can do that on the hosting web server (I don't know what is running there).

**Comment by PalmJanssen** [comment]
Seems a good idea. @lvdbrink How to proceed?

**Comment by lvdbrink** [comment]
If @jechterhoff can clarify for us what are the requirements for hosting the file, we can check with tech support if they can accomodate that.

**Comment by jechterhoff** [comment]
@lvdbrink The JSON Schema file(s) should be publicly available, and served with mime type `application/schema+json`, even if the file extension is `.json`.

**Comment by wilkoquak** [comment]
I can answer the question. Yes we can host it on register.geostandaarden.nl and yes it is possible to serve a specific mime type for a specific version.

**Comment by wilkoquak** [comment]
I moved the schema to: https://register.geostandaarden.nl/jsonschema/uml2json/0.1/schema_definitions.json . I am not 100% sure the mime-type is set correctly that needs some more work.

**Comment by PalmJanssen** [comment]
Closed as completed
