### ISSUE TITLE
Figure 11: uses <<type>> stereotype that is not mentioned in Table 2.

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/uml2json#30]
Table 2 lists the relevant stereotypes but the `<<type>>` stereotype that is used in Figure 11 is not mentioned.

**Comment by jechterhoff** [comment]
Table 2 states: 

> interface — for backwards-compatibility to UML 1 schemas (that comply with earlier versions of [ISO 19103:2015](file:///C:/REPOSITORIES/Geonovum/uml2json/document.html#ref_iso19103)) also: type

Indeed, though, `<<type>>` is maybe something to avoid in our examples. Then again, that is part of the larger discussion about the use of UML profiles and UML version in the specification.
