### ISSUE TITLE
Different target type

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/uml2json#33]
According to clause 2, Conformance:

> The standardization target for all these classes are JSON (Schema) documents

However, in the tables describing the requirements classes, the target type is specified as “JSON (Schema) Encoding” or “JSON Schema Encoding”.

This should be the same everywhere, for consistency.

**Comment by PalmJanssen** [comment]
Agree.

**Comment by jechterhoff** [comment]
Now "JSON (Schema) documents" is used consistently.
