### ISSUE TITLE
Requirement requiring conformance to the JSON Schema Core spec

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/uml2json#34]
I would expect the first requirement to be:

A JSON Schema encoding shall conform to _JSON Schema: A Media Type for Describing JSON Documents_.

And because of that requirement, _JSON Schema: A Media Type for Describing JSON Documents_ becomes a normative reference (at least when following the ISO rules for when a specification is a normative reference, see also https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor193, but I believe OGC follows the same rules?).

It seems that an older specification is referenced, is that on purpose? The latest one seems to be available at the following links:
- https://json-schema.org/draft/2020-12/json-schema-core.html
- https://www.ietf.org/archive/id/draft-bhutton-json-schema-01.html

**Comment by heidivanparys** [comment]
Perhaps the OGC way of expressing this is to add _JSON Schema: A Media Type for Describing JSON Documents_, as a dependency/prerequisite? I don't know how OGC references other specifications that don't follow the modular specification.

**Comment by jechterhoff** [comment]
The first requirement presents a choice of which JSON Schema version is used. 

> The “$schema” keyword shall be added to the definitions schema. Its value shall be one of:
> * https://json-schema.org/draft/2019-09/schema
> * https://json-schema.org/draft/2020-12/schema

This allows schema generation in either format, in support of different deployment scenarios where the JSON Schema validator may or may not support one or the other JSON Schema version. The relevant IETF documents for both versions are cited as normative reference.

I know that having such options / choices is not ideal for interoperability. However, in the case of this specification, it provides flexibility for practical reasons.

If we settled on one particular version - likely 2020-12 - then we could add the according IETF documents as dependencies.

**Comment by jechterhoff** [comment]
Having discussed this with @PalmJanssen, we decided to remove the choice, and use the 2020-12 JSON Schema.
