### ISSUE TITLE
Requirement 14 (/req/core/property-multiplicity)

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/uml2json#39]
The statement uses the term “cardinality” several times, this should be replaced with “multiplicity”.

**Comment by PalmJanssen** [comment]
That's alway a point. I would say that multiplicity defines the range of possible cardinalities. So a statement like 'the minimum cardinality is 0' is correct.

**Comment by jechterhoff** [comment]
Now using "multiplicity lower bound" and "multiplicity upper bound".
