### ISSUE TITLE
Geometries in plain JSON: explain choice for GeoJSON geometries

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/uml2json#42]
For the geometries in plain JSON, (only) the GeoJSON schemas for the geometries are used. It would be useful to add the reasoning behind this choice in the best practice.

In previous [engineering reports](https://www.ogc.org/docs/er), the possibility of using WKT has been explored, with arguments in favour and against.

WKT in JSON is also supported by e.g. FME, see https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/json/JSON_reader.htm and screenshot below.

![image](https://user-images.githubusercontent.com/11427611/214092766-8ac0a0fb-b615-447a-83ea-e23a73d76f9f.png)

**Comment by jechterhoff** [comment]
If I remember correctly, we stated this as a requirement to improve interoperability. But I see your point.

Proposal: Switch the requirement to a recommendation. Add a note which explains that other geometry encodings are allowed in plain JSON, for example a WKT string or a JSON-FG geometry.

@heidivanparys and @PalmJanssen: What do you think?

**Comment by heidivanparys** [comment]
Change the requirement to a recommendation is ok with me.

**Comment by jechterhoff** [comment]
Done.

Note that the plain JSON Schema format requirements class now only has a recommendation, no additional requirement. That may look weird, but is ok according to the OGC specification model (OGC 08-131r3; Figure C.1). Furthermore, the plain JSON Schema format requirements class depends on the abstract Core requirements class. Thus, all the requirements defined there apply to the plain JSON Schema encoding.
