### ISSUE TITLE
Need for recommendation 2 (/req/core/schema-publication-media-type)

### ISSUE THREAD

**Issue by heidivanparys** [Geonovum/uml2json#43]
As _JSON Schema: A Media Type for Describing JSON Documents_ is/should be a dependency of requirements class core (#34), recommendation 2 regarding the media type is redundant, it repeats a recommendation from that specification. If it is important to mention that recommendation in the best practice (which it probably is), it should be in e.g. the main text or in a note of the best practice.

**Comment by jechterhoff** [comment]
We can also make it normal text. @PalmJanssen: What do you think?

**Comment by PalmJanssen** [comment]
agreed
