### ISSUE TITLE
Comparison with INSPIRE requirements for JSON encoding

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/uml2json#49]
I have compared the [document](https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/geojson-encoding-rule.md#inspire-requirements-for-encoding-rules) describing the outcome of [Action 2017.2](https://webgate.ec.europa.eu/fpfis/wikis/x/aAKOE) on alternative encodings for INSPIRE data with the document as set up in this repository.

The only significant difference that I found was with basic types Measures and Length and how to deal with unit of measurement.

INSPIRE requires [Measures and Lenght](https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/geojson-encoding-rule.md#iso-19103---basic-types)  to be converted to doubles. Secondly it requires to add a property named x with an unit of measurement to be mapped to an extra property with the name [x.uom](https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/geojson-encoding-rule.md#properties-with-a-uom-attribute).

The UML2JSON document as setup in this repository gives 2 options: [option 1](https://geonovum.github.io/uml2json/document.html#annex_uml2json_schema_definition): It stays or becomes a Measure object with “value” (number) and “uom” (string) as properties and [option 2](https://geonovum.github.io/uml2json/document.html#_8cc0bf60-77c2-f6b9-4791-965d666a957a): use keyword "unit" like "type" to describe the property.

**Comment by jechterhoff** [comment]
@PB-GNM and @PalmJanssen: This issue looks more like a statement of fact, and not an actual issue. Can we close it?

**Comment by PalmJanssen** [comment]
This document is based on and extends the results of [OGC Engineering report UGAS-2020](https://docs.ogc.org/per/20-012.html) regarding JSON Schema encoding rules. This is someting else then the Inspire UML-to-GeoJSON document developed in the Inspire context.

Both documents have more differences then mentioned. In general the UGAS and the evolved UML to JSON doc is more detailed and profound and aligned with OGC Api Features and of cource includes also JSON-FG.

The differences are considered as noted and are not part of the requirements set for this document.
