### ISSUE TITLE
1 Scope - pja - Mention UML profile 19103/19109

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#5]
Mention the ISO 19103/19109 as the UML profile that is used in this encoding specification

**Comment by jechterhoff** [comment]
How about the following (added text in bold): This document defines requirements for encoding application schemas in UML, **which conform to the UML profile defined by ISO 19103 and potentially also ISO 19109,** as JSON schemas.

**Comment by PalmJanssen** [comment]
Perfect!

**Comment by jechterhoff** [comment]
Decision: JE to update as proposed
