### ISSUE TITLE
Requirement 21 (/req/geojson-formats/identifier)

### ISSUE THREAD

**Issue by jechterhoff** [Geonovum/uml2json#51]
Right now, requirement /req/geojson-formats/identifier is only for actual JSON data, where a value for the id-member is expected. No specific JSON Schema constraints are created for the id-member. However, we could encode such constraints (simply require the id-member). /req/geojson-formats/identifier could be modified to create such constraints.

**Comment by jechterhoff** [comment]
@PalmJanssen Not sure if we actually need to create an actual JSON Schema contraint to require the GeoJSON "id" member, at this point in time. We could defer this to future work and close this issue (it can be re-opened any time). What do you think?

**Comment by PalmJanssen** [comment]
up to you. So not for now.
