### ISSUE TITLE
2 Conformance - pja - revise reference to Annex A

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#6]
Since there is no conformance test this text should be revised.

Question: Did we decide to not have a conformance test? I read in Annex A that that is something for the next step in the OGC proces.

**Comment by lvdbrink** [comment]
I don't remember - but since we don't have them at the moment, I agree we should revise the last few sentences of chapter 2.

**Comment by jechterhoff** [comment]
Decision: Revise the text at the end of chapter 2 to explain the intent.
