### ISSUE TITLE
4.1.2 - pja - <<FeatureType>>

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#7]
The stereotype feature type is since 19109:2015 \<\<FeatureType>>

**Comment by jechterhoff** [comment]
Can be changed to `<<FeatureType>>`, though then we will probably have to change this throughout the spec. Not a big deal for the text, but more work for the example diagrams. We'd have to update the UML profile. The definition of the UML profile is a bigger discussion item (see #13).

**Comment by jechterhoff** [comment]
Decision: 

* Update Stereotype names within the text, leave them in diagrams as is
* Discuss in conventions the lower- and upper-case usage in the document

In the future, stereotypes in diagrams should also be updated.
