### ISSUE TITLE
6 Overview - pja - Mention the iso 19103 as part of the UML profile

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/uml2json#8]
I would expect the ISO 19103 to be mentioned as the ISO TC 211 profile on UML

**Comment by jechterhoff** [comment]
How about the following (addition in bold): A couple of these Standards, especially **ISO 19103 and** ISO 19109, are used by the geospatial community [...]

**Comment by jechterhoff** [comment]
Decision: The UML profiles defined by ISO 19103 and also ISO 19109 is used as the base UML profile in this document.
